"""CLI command to control the Database."""

import asyncio
from typing import Optional

import typer
from alembic import command
from alembic.config import Config
from rich import print as rprint
from sqlalchemy import text

from app.database.db import async_session

app = typer.Typer(no_args_is_help=True, rich_markup_mode="rich")

ALEMBIC_CFG = Config("alembic_scripting.ini")
DONE_MSG = "[green]Done!"


async def _drop_enum_type() -> None:
    """Drop the roletype enum type."""
    async with async_session() as session:
        await session.execute(text("DROP TYPE IF EXISTS roletype CASCADE;"))
        await session.commit()


@app.command()
def init(
    force: Optional[bool] = typer.Option(
        False,
        "--force",
        "-f",
        prompt=(
            "Warning! This deletes all data in the database. Are you sure?"
        ),
        help="Do not ask for confirmation.",
    ),
) -> None:
    """Re-Initialise the database using Alembic.

    This will create the database if it does not exist, and run all migrations.
    If the database already exists, it will be dropped and recreated.
    """
    if force:
        rprint("\nInitialising Database ... ", end="")

        command.downgrade(ALEMBIC_CFG, "base")
        asyncio.run(_drop_enum_type())
        command.upgrade(ALEMBIC_CFG, "head")
        rprint(DONE_MSG)
    else:
        rprint("[cyan]Operation Cancelled.")


@app.command()
def drop(
    force: Optional[bool] = typer.Option(
        False,
        "--force",
        "-f",
        prompt=(
            "Warning! This deletes all data in the database. Are you sure?"
        ),
        help="Do not ask for confirmation.",
    ),
) -> None:
    """Drop all tables and reset the Database.

    This will delete all data from your Database!.
    """
    if force:
        rprint("\nDropping all tables ... ", end="")

        command.downgrade(ALEMBIC_CFG, "base")
        asyncio.run(_drop_enum_type())
        rprint(DONE_MSG)
    else:
        rprint("[cyan]Operation Cancelled.")


@app.command()
def upgrade() -> None:
    """Apply the latest Database Migrations."""
    rprint("\nUpgrading Database ... ", end="")

    command.upgrade(ALEMBIC_CFG, "head")
    rprint(DONE_MSG)


@app.command()
def revision(
    message: str = typer.Option(
        ...,
        "--message",
        "-m",
        prompt=("Enter the commit message for the revision"),
        help="Provide a message for this commit.",
    ),
) -> None:
    """Create a new revision.

    The revision will be created in the `alembic/versions` directory, and is
    autogenerated based on the current state of the database.
    """
    rprint()
    command.revision(ALEMBIC_CFG, message=message, autogenerate=True)
    command.upgrade(ALEMBIC_CFG, "head")
