"""Add verified flag

Revision ID: 4cab6fd22890
Revises: 3ef701c22cf8
Create Date: 2022-12-08 15:30:55.609137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4cab6fd22890"
down_revision = "3ef701c22cf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verified")
    # ### end Alembic commands ###
