"""Add Token blacklist table

Revision ID: b94f4d3695bb
Revises: 4cab6fd22890
Create Date: 2023-04-30 16:02:41.343514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b94f4d3695bb"
down_revision = "4cab6fd22890"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
