name: Type Checking

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    # uncomment the line before to disable this job if needed.
    # if: false
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Run mypy
        run: uv run --all-extras mypy . --strict
