name: Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
        with:
          args: " check --output-format=concise"
      - run: ruff format --check
